services:
  api-discovery-server:
    image: elleined/api-discovery-server:${IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      - TZ=Asia/Manila
      - PORT=${DISCOVERY_SERVER_PORT}
      - LOG_LEVEL=${LOG_LEVEL}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    ports:
      - "${DISCOVERY_SERVER_PORT}:${DISCOVERY_SERVER_PORT}"
    networks:
      - dev-api-gateway-network
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://${CONTAINER_NAME}:${DISCOVERY_SERVER_PORT}/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  dev-api-gateway-network:
    name: ${NETWORK_NAME}
    external: false
    ipam:
      driver: default