version: "3.8"
services:
  api_gateway:
    image: elleined/api-gateway:latest
    container_name: api_gateway
    env_file:
      - api_gateway.env
    networks:
      - api_gateway_network
    depends_on:
      api_discovery_server:
        condition: service_healthy
  api_discovery_server:
    image: elleined/api-discovery-server:latest
    container_name: api_discovery_server
    env_file:
      - api_discovery_server.env
    networks:
      - api_gateway_network
    healthcheck:
      test: curl http://localhost:8761/actuator/health
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 120s
networks:
  api_gateway_network:
    name: api_gateway_network
    external: false
    ipam:
      driver: default